@startuml
circle first as "initial \ncommit"
circle second as " "
circle third as " "
circle fourth as " "
card MASTER
card HEAD
first <-right- second
second <-right- third
MASTER --> third
HEAD --> third
fourth -down->first
@enduml