@startuml
circle first as "initial \ncommit\n3fb9399"
circle second as " "
circle third as "last\ncommit"
card MASTER
card HEAD
first <-right- second
second <-right- third
MASTER --> third
HEAD --> third
@enduml