@startuml
left to right direction

class Mitglied {
  vorname: String
  nachname: String
}

class Zahlungsvorgang {
  zahlungsart: Zahlungsart
  mitglied: Mitglied
  zahlungsdatum: LocalDate
  betrag: BigInteger
}

class Zahlungsart {
  bezeichnung: String
}

note bottom of Zahlungsart
  Bsp für Zahlungsvorgang:
  - Einzahlung
  - Auszahlung
  - Strafe
end note

Mitglied "1" <-- "*" Zahlungsvorgang
Zahlungsvorgang "*" --> "1" Zahlungsart

@enduml
